apiVersion: v1
kind: Service
metadata:
  name: {{ resource_name }}
  namespace: {{ namespace }}
  labels:
    app: {{ service_name }}
spec:
  selector:
    app: {{ service_name }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: {{ port | default(8000) }}
  type: ClusterIP
